version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    groups:
      nuget-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Amsterdam
    groups:
      github-actions:
        patterns:
          - "*"
