#Requires -Version 7.0
[CmdletBinding()]
param([switch] $Check)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dataPath = Join-Path $root 'eng/compatibility.json'
$outputPath = Join-Path $root 'docs/compatibility.md'
$data = Get-Content -LiteralPath $dataPath -Raw | ConvertFrom-Json

if ($data.schemaVersion -ne 1) { throw "Unsupported compatibility schema: $($data.schemaVersion)" }

$manifest = @(Get-Content -LiteralPath (Join-Path $root 'eng/package-manifest.txt') |
    Where-Object { $_ -and !($_.StartsWith('#')) } | ForEach-Object Trim)
$declaredPackages = @($data.packages | ForEach-Object id)
$packageDifference = Compare-Object $manifest $declaredPackages
if ($packageDifference) {
    throw "eng/compatibility.json packages must exactly match eng/package-manifest.txt:`n$($packageDifference | Out-String)"
}

[xml] $buildProps = Get-Content -LiteralPath (Join-Path $root 'Directory.Build.props') -Raw
$targetFramework = [string]($buildProps.Project.PropertyGroup.TargetFramework | Select-Object -First 1)
$global = Get-Content -LiteralPath (Join-Path $root 'global.json') -Raw | ConvertFrom-Json
$sdkVersion = [string]$global.sdk.version
$testRunner = [string]$global.test.runner

[xml] $packageProps = Get-Content -LiteralPath (Join-Path $root 'Directory.Packages.props') -Raw
$packageVersions = @{}
foreach ($node in $packageProps.SelectNodes('//PackageVersion')) {
    $packageVersions[[string]$node.Include] = [string]$node.Version
}

$workflowText = Get-Content -LiteralPath (Join-Path $root '.github/workflows/test-suites.yml') -Raw
$suiteMatches = [regex]::Matches(
    $workflowText,
    '(?m)^\s*-\s+suite:\s*(?<suite>[^\r\n]+)\r?\n\s+project:\s*(?<project>[^\r\n]+)\s*$')
$workflowSuites = @{}
foreach ($match in $suiteMatches) {
    $workflowSuites[$match.Groups['suite'].Value.Trim()] = $match.Groups['project'].Value.Trim()
}

$declaredSuiteNames = @($data.scenarios | ForEach-Object name)
$suiteDifference = Compare-Object @($workflowSuites.Keys | Sort-Object) @($declaredSuiteNames | Sort-Object)
if ($suiteDifference) {
    throw "Compatibility scenarios must exactly match the test suite matrix:`n$($suiteDifference | Out-String)"
}
foreach ($scenario in $data.scenarios) {
    if ($workflowSuites[$scenario.name] -ne $scenario.project) {
        throw "Scenario '$($scenario.name)' must reference '$($workflowSuites[$scenario.name])'."
    }
    if (!(Test-Path -LiteralPath (Join-Path $root $scenario.project))) {
        throw "Scenario project does not exist: $($scenario.project)"
    }
}

$frameworkMatch = [regex]::Match($workflowText, 'framework:\s*\[(?<items>[^\]]+)\]')
if (!$frameworkMatch.Success) { throw 'Framework CI matrix was not found.' }
$workflowFrameworks = @($frameworkMatch.Groups['items'].Value.Split(',') | ForEach-Object Trim)
$declaredFrameworks = @($data.frameworks | ForEach-Object matrixName)
$frameworkDifference = Compare-Object @($workflowFrameworks | Sort-Object) @($declaredFrameworks | Sort-Object)
if ($frameworkDifference) {
    throw "Compatibility frameworks must exactly match the CI matrix:`n$($frameworkDifference | Out-String)"
}
foreach ($framework in $data.frameworks) {
    if (!$packageVersions.ContainsKey($framework.versionPackage)) {
        throw "Package version not found for framework '$($framework.name)': $($framework.versionPackage)"
    }
    if (!(Test-Path -LiteralPath (Join-Path $root $framework.project))) {
        throw "Framework project does not exist: $($framework.project)"
    }
}
foreach ($package in $data.packages) {
    if (!$workflowSuites.ContainsKey($package.evidence)) {
        throw "Package '$($package.id)' references unknown evidence suite '$($package.evidence)'."
    }
    if (!(Test-Path -LiteralPath (Join-Path $root "docs/$($package.guide)"))) {
        throw "Package '$($package.id)' references missing guide '$($package.guide)'."
    }
}

$repository = 'https://github.com/cokceken/stove-dotnet'
$builder = [Text.StringBuilder]::new()
function Add-Line([string] $Line = '') { [void]$builder.AppendLine($Line) }

Add-Line '<!-- Generated by scripts/generate-compatibility.ps1. Edit eng/compatibility.json or the referenced build files. -->'
Add-Line '# Compatibility and trust'
Add-Line
Add-Line '[![CI](https://github.com/cokceken/stove-dotnet/actions/workflows/ci.yml/badge.svg?branch=main&event=push)](https://github.com/cokceken/stove-dotnet/actions/workflows/ci.yml?query=branch%3Amain)'
Add-Line '[![Documentation](https://github.com/cokceken/stove-dotnet/actions/workflows/pages.yml/badge.svg?branch=main&event=push)](https://github.com/cokceken/stove-dotnet/actions/workflows/pages.yml?query=branch%3Amain)'
Add-Line '[![OpenSSF Scorecard](https://api.scorecard.dev/projects/github.com/cokceken/stove-dotnet/badge)](https://scorecard.dev/viewer/?uri=github.com/cokceken/stove-dotnet)'
Add-Line
Add-Line 'A checkmark means the capability is exercised by the default-branch CI pipeline. It is not a promise about platforms or versions outside the matrix below. Follow the evidence links to inspect the executable test projects and workflow history.'
Add-Line
Add-Line '## Runtime and environment'
Add-Line
Add-Line '| Capability | Verified value | Status |'
Add-Line '|---|---|---:|'
Add-Line "| Target framework | ``$targetFramework`` | ✅ CI verified |"
Add-Line "| .NET SDK | ``$sdkVersion`` with ``$($global.sdk.rollForward)`` roll-forward | ✅ CI verified |"
Add-Line "| Test runner | ``$testRunner`` | ✅ CI verified |"
Add-Line '| CI operating system | GitHub-hosted `ubuntu-latest` | ✅ CI verified |'
Add-Line '| Container runtime | Docker API through Testcontainers on the GitHub runner | ✅ CI verified |'
Add-Line '| Windows and macOS | Not in the CI matrix | Not claimed |'
Add-Line '| Podman | Supported as a Docker-compatible local runtime | Not continuously verified |'
Add-Line
Add-Line '## Test frameworks'
Add-Line
Add-Line 'Each framework consumer is built and run in full, filtered, intentionally failing and skipped modes. CI also verifies once-per-run startup, teardown and client cleanup.'
Add-Line
Add-Line '| Framework | Version | Verification | Evidence |'
Add-Line '|---|---:|---:|---|'
foreach ($framework in $data.frameworks) {
    $version = $packageVersions[$framework.versionPackage]
    $evidenceUrl = "$repository/tree/main/$($framework.project)"
    Add-Line "| $($framework.name) | ``$version`` | ✅ CI verified | [Consumer project]($evidenceUrl) |"
}
Add-Line
Add-Line '## Release package surface'
Add-Line
Add-Line 'Every listed package must appear in the release manifest, produce both package and symbol artifacts, restore from an isolated local feed, and compile in the package smoke test before publication.'
Add-Line
Add-Line '| Package | Area | Purpose | Behavioral evidence |'
Add-Line '|---|---|---|---|'
foreach ($package in $data.packages) {
    $nugetUrl = "https://www.nuget.org/packages/$($package.id)"
    $scenario = $data.scenarios | Where-Object name -eq $package.evidence | Select-Object -First 1
    $evidenceUrl = "$repository/tree/main/$($scenario.project)"
    Add-Line "| [``$($package.id)``]($nugetUrl) | $($package.area) | [$($package.purpose)]($($package.guide)) | ✅ [$($package.evidence)]($evidenceUrl) |"
}
Add-Line
Add-Line '## Executable scenarios'
Add-Line
Add-Line '| CI suite | What it verifies | Evidence |'
Add-Line '|---|---|---|'
foreach ($scenario in $data.scenarios) {
    $evidenceUrl = "$repository/tree/main/$($scenario.project)"
    Add-Line "| $($scenario.name) | $($scenario.area) | ✅ [Test project]($evidenceUrl) |"
}
Add-Line
Add-Line '## Security and release controls'
Add-Line
Add-Line '| Control | Status | Public evidence |'
Add-Line '|---|---:|---|'
Add-Line "| Pull-request CI and package verification | ✅ Enforced | [CI workflow]($repository/actions/workflows/ci.yml) |"
Add-Line "| Static analysis | ✅ CodeQL | [CodeQL runs]($repository/actions?query=workflow%3ACodeQL) |"
Add-Line "| Dependency changes | ✅ Reviewed on pull requests | [Dependency review workflow]($repository/actions/workflows/dependency-review.yml) |"
Add-Line "| Supply-chain posture | ✅ Independently scored | [OpenSSF Scorecard](https://scorecard.dev/viewer/?uri=github.com/cokceken/stove-dotnet) |"
Add-Line "| NuGet authentication | ✅ Environment-bound OIDC; no long-lived API key | [Release security](release-security.md) |"
Add-Line "| Actions dependencies | ✅ Full commit SHA pins | [Workflow sources]($repository/tree/main/.github/workflows) |"
Add-Line "| Vulnerability reporting | ✅ Private reporting enabled | [Security policy]($repository/security/policy) |"
Add-Line
Add-Line 'Security scanners reduce risk but cannot prove the absence of vulnerabilities. See the [security policy](https://github.com/cokceken/stove-dotnet/security/policy) to report an issue privately.'

$content = $builder.ToString().Replace("`r`n", "`n")
if ($Check) {
    if (!(Test-Path -LiteralPath $outputPath)) { throw 'docs/compatibility.md is missing. Run scripts/generate-compatibility.ps1.' }
    $existing = (Get-Content -LiteralPath $outputPath -Raw).Replace("`r`n", "`n")
    if ($existing -ne $content) { throw 'docs/compatibility.md is stale. Run scripts/generate-compatibility.ps1 and commit the result.' }
    Write-Host 'Compatibility documentation is current.'
} else {
    [IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
    Write-Host "Generated $outputPath"
}
